import type {
    ShapeStyle,
} from './model';

/** Identifier for each selectable tool in the freeform drawing editor. */
export type ToolId = 'select'
| 'hand'
| 'pencil'
| 'pen'
| 'highlighter'
| 'rect'
| 'ellipse'
| 'line'
| 'connector'
| 'text'
| 'eraser';

/** Minimum/maximum zoom factor the navigator is clamped to. */
export const SCALE_EXTENT: [number, number] = [0.02, 64];

/** Default drawing style applied to newly created shapes. */
export const DEFAULT_STYLE: ShapeStyle = {
    stroke: '#1e1e1e',
    fill: null,
    strokeWidth: 4,
    opacity: 1,
    dash: false,
};

/** Curated color swatches offered in the style panel (tuned for the light canvas). */
export const PALETTE: string[] = [
    '#1e1e1e',
    '#e03131',
    '#f08c00',
    '#f59f00',
    '#2f9e44',
    '#1971c2',
    '#6741d9',
    '#e64980',
    '#868e96',
    '#ffffff',
];

/** Alpha applied to highlighter strokes so overlapping marks read as translucent ink. */
export const HIGHLIGHTER_ALPHA = 0.4;

/** Multiplier applied to the base stroke width when drawing with the highlighter. */
export const HIGHLIGHTER_WIDTH_SCALE = 6;

/** Dash pattern (in world units) used when a shape's `dash` style is enabled. */
export const DASH_PATTERN: [number, number] = [10, 8];

/** Minimum world-space distance between successive freehand sample points. */
export const FREEHAND_MIN_DISTANCE = 2;

/** Side length, in screen pixels, of a selection resize handle. */
export const HANDLE_SIZE = 9;

/** Extra world-space padding added around a shape's geometry when hit testing strokes. */
export const HIT_TOLERANCE = 8;

/** Number of shapes generated by the performance stress-test action. */
export const STRESS_TEST_COUNT = 5000;
