name: Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Test report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: .reports/test-results.xml
          reporter: java-junit

      - name: Coverage report
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          vite-config-path: vitest.config.ts
          json-summary-path: .reports/coverage/coverage-summary.json
          json-final-path: .reports/coverage/coverage-final.json
